### ISSUE TITLE
Inconsistency with data URLs

### ISSUE THREAD

**Issue by xiam** [goware/urlx#3]
Hello @VojtechVitek,

It is not clear to me what `urlx.Parse()` is supposed to do when faced against certain URLs like these:

```
 // Funny strings
{in: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==", err: true},
{in: "javascript:evilFunction()", err: true},
{in: "otherscheme:garbage", err: true},
{in: "<funnnytag>", err: true},
```

Right now `Parse()` prepends `http://` to the string and it ends up accepting all those funny strings as valid hostnames, even though none of them are http URLs. (In the case of the data url the scheme will end un being `data` and the hostname `image` with a path that begins with `/png;base64,...`).

Maybe we should check that the host value we extract is also a FQDN? and reject all URLs that don't have a valid FQDN. This will take care of the above cases but will also produce errors in cases like `localhost:80`, because `80` is not a FQDN (the `localhost` part is interpreted as a schema), which I think is OK because users should not normally point to hosts like those.

**Comment by VojtechVitek** [comment]
Yea, I agree, let's clear this up.

Imho, the `"localhost:8080"` should be valid though.
