### ISSUE TITLE
Invalid checking of domain names

### ISSUE THREAD

**Issue by nielsole** [goware/urlx#6]
Stumbled upon this due to this: https://github.com/codesenberg/bombardier/issues/39

https://github.com/goware/urlx/blob/06d8eeb3ce171b5617a3f8ef24451df26ca971ef/urlx.go#L65-L77

single segment hostnames are perfectly valid. You can not make the assumption that every domain has a subdomain. 

Maybe only accepting only public domains is something you want, but then maybe https://godoc.org/golang.org/x/net/publicsuffix is better suited? (I honestly don't know if it is better) The current solution just has inconsistent results either way e.g. co.uk is not a publicly used domain, but co.de is.

**Comment by VojtechVitek** [comment]
Please, open a Pull Request with suggested changes. Thanks
