### ISSUE TITLE
[BUG] if the url contains '_' the urlx will return error

### ISSUE THREAD

**Issue by 0xrishabh** [goware/urlx#9]
https://goplay.space/#A2P8L8lY93H

**Comment by 0xrishabh** [comment]
I think this the problem, the regex is not sufficient -

`domainRegexp = regexp.MustCompile(`^([a-zA-Z0-9-]{1,63}\.)*([a-zA-Z0-9-]{1,63})$`)`

**Comment by VojtechVitek** [comment]
Thanks for the bug report. I guess this could be allowed for subdomains, but not domains, am I right?

Can you point us at RFC clearly saying this character can be part of the subdomain?

Are you going to provide a PR?

**Comment by 0xrishabh** [comment]
Yes, it is allowed for subdomains
RFC? No, I can't and I think probably this '_' character in subdomain is one of those things that differ in RFC and real-life implementations all major browsers and DNS servers allow _ in the subdomain.
The only thing I found closest to this issue is in **rfc 1034** 
`The labels must follow the rules for ARPANET host names.  They must
start with a letter, end with a letter or digit, and have as interior
characters only letters, digits, and hyphen.  There are also some
restrictions on the length.  Labels must be 63 characters or less.`

And the about the PR I don't think I can, I am just not enough qualified to write golang code
